# This file was generated by GoReleaser. DO NOT EDIT.
cask "sortie" do
  version "1.19.0"

  on_macos do
    on_intel do
      sha256 "210db239f6a5e2c11cccfbf9a7d070d434a62eaba11510ec31c15b4568319b56"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/sortie-ai/sortie/"
    end
    on_arm do
      sha256 "905a43cb4e0fa3f459cac0e41dc76054d07fc11d0506f8ca08e0f43e8ee2dca9"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/sortie-ai/sortie/"
    end
  end

  on_linux do
    on_intel do
      sha256 "594e8105c286c09dae072629f5497c0e9aa36876f9c8cc8271490197d19ccd20"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_linux_amd64.tar.gz",
        verified: "github.com/sortie-ai/sortie/"
    end
    on_arm do
      sha256 "a9c8eb8b56f230c1d9c2f897424dd5f115a5b48264b5cfba6091c4a2fc255c2a"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_linux_arm64.tar.gz",
        verified: "github.com/sortie-ai/sortie/"
    end
  end

  name "sortie"
  desc "Spec-first orchestration service for coding agents"
  homepage "https://github.com/sortie-ai/sortie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sortie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sortie"],
        must_succeed: false
    end
  end

  # No zap stanza required

end
