# This file was generated by GoReleaser. DO NOT EDIT.
cask "sortie" do
  version "1.20.0"

  on_macos do
    on_intel do
      sha256 "1713374a9ca18b958deff73f93eb2ebbcf4e2e737d14eddcd80d3ffec088dcc7"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/sortie-ai/sortie/"
    end
    on_arm do
      sha256 "15d00d86857a564f5a02ca59572b5e18a6a21e60c5f3cf1798ae8a5458780c99"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/sortie-ai/sortie/"
    end
  end

  on_linux do
    on_intel do
      sha256 "361d4a172468c17f5e2ad48c2eaf2f46770af97ffc1034fa9f3c8a4ab32851d7"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_linux_amd64.tar.gz",
        verified: "github.com/sortie-ai/sortie/"
    end
    on_arm do
      sha256 "7ee1667e4c6b02381271606cb30326692d793bcaf84f1d55fcaf218e6f0cef80"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_linux_arm64.tar.gz",
        verified: "github.com/sortie-ai/sortie/"
    end
  end

  name "sortie"
  desc "Spec-first orchestration service for coding agents"
  homepage "https://github.com/sortie-ai/sortie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sortie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sortie"],
        must_succeed: false
    end
  end

  # No zap stanza required

end
