# This file was generated by GoReleaser. DO NOT EDIT.
cask "sortie" do
  version "1.24.1"

  on_macos do
    on_arm do
      sha256 "2af4924f80def5b814950ac07fc8261858e9bb1543b395747231fa412627be0b"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f21e51d492ae2c15acd383c05dd32a3bcaa20dd75f4eac85423759339f3970b0"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1c48c30bdfa10858c65c226711cc9a0e68e3bbe3a2d52475af020762521908cb"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b943a50d389f1883b98ccd590884d5fb1e045e80dddea5fe62df6e15c249dffe"
      url "https://github.com/sortie-ai/sortie/releases/download/v#{version}/sortie_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sortie"
  desc "Spec-first orchestration service for coding agents"
  homepage "https://github.com/sortie-ai/sortie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sortie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sortie"],
        must_succeed: false
    end
  end

  # No zap stanza required
end
