# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sortie < Formula
  desc "Spec-first orchestration service for coding agents"
  homepage "https://github.com/sortie-ai/sortie"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sortie-ai/sortie/releases/download/1.1.0/sortie_1.1.0_darwin_amd64.tar.gz"
      sha256 "9cb07f2a58f2586ed770360ee75c4c1a81e5d7b57d2a64e8b46685a2a56d0017"

      define_method(:install) do
        bin.install "sortie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sortie-ai/sortie/releases/download/1.1.0/sortie_1.1.0_darwin_arm64.tar.gz"
      sha256 "b310af586cb5cac670ba875d8bed5c9221dc02075841d06e16915a8c1429c07f"

      define_method(:install) do
        bin.install "sortie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sortie-ai/sortie/releases/download/1.1.0/sortie_1.1.0_linux_amd64.tar.gz"
      sha256 "9d683ef5c006394dcd7cab2061e0797d9656d1d1a392e34413fead44658aa411"
      define_method(:install) do
        bin.install "sortie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sortie-ai/sortie/releases/download/1.1.0/sortie_1.1.0_linux_arm64.tar.gz"
      sha256 "dbf547be2d81da760def9d16263a649ba4838f14791a0d65a3a029d09f0efa0e"
      define_method(:install) do
        bin.install "sortie"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sortie --version")
  end
end
